// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBB1fSguiv-HCU3idZbprW-ifZg-wOhfk',
    appId: '1:333042435736:web:f247deac9aba86bb77f2ed',
    messagingSenderId: '333042435736',
    projectId: 'local-phone-book-app',
    authDomain: 'local-phone-book-app.firebaseapp.com',
    storageBucket: 'local-phone-book-app.appspot.com',
    measurementId: 'G-1V50FCVL04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0kN-aoyRuN-_t8LWN3nJN7etWDb3fpPQ',
    appId: '1:333042435736:android:bea6c7bbca3c97b877f2ed',
    messagingSenderId: '333042435736',
    projectId: 'local-phone-book-app',
    storageBucket: 'local-phone-book-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHpJqYGDZBF_r6TdfhO6xmnPFDW2ZUCH0',
    appId: '1:333042435736:ios:10d4a1b431f4ace577f2ed',
    messagingSenderId: '333042435736',
    projectId: 'local-phone-book-app',
    storageBucket: 'local-phone-book-app.appspot.com',
    iosBundleId: 'com.example.localTelephoneDairy',
  );
}
